config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end

  get 'users/new'

  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/help'

  get '/checklist', to: 'checklist#checklist'

  get 'registration/registration'

  get 'checklist/new'

  root 'registration#registration'

  get '/signup', to: "users#new"

  resources :users

end

app/models/checklist_item.rb
class ChecklistItem < ActiveRecord::Base
  belongs_to :user
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :checklist_items, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/checklist_controller.rb
class ChecklistController < ApplicationController

  def checklist
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def new
  end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @checklist_items = @user.checklist_items.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Weddly!"
      redirect_to @user
      # Handle a successful save.
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklist_helper.rb
module ChecklistHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
 def gravatar_for(user)
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
   image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/views/checklist/checklist.html.erb
<%= stylesheet_link_tag params[:controller] %>
<li id="checklist_item-<%= checklist_item.id %>">
  <%= link_to gravatar_for(checklist_item.user, size: 50), checklist_item.user %>
  <span class="user"><%= link_to checklist_item.user.name, checklist_item.user %></span>
  <span class="content"><%= checklist_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(checklist_item.created_at) %> ago.
  </span>
</li>
<div class='container'>
  <div class="header">
    <div class="logo">
      <img src="http://blog.weddly.co/wp-content/uploads/2016/08/logo-3-1.png" class="logo">
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="menu col-md-3">
        <div class="leftMenu">
          <h3>Łukasz and Renata</h3>
          <div class="row">
            <div class="col-md-6">
              Do zrobienia
            </div>
            <div class="col-md-6">
              6
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              Zrobione
            </div>
            <div class="col-md-6">
              3
            </div>
          </div>
        </div>
      </div>
      <div class="checklist col-md-5">
        <div class="month">
          <h3>August</h3>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
      </div>
      <div class="menu3 col-md-4">
        <div class="item">
          New item
        </div>
        <div class="item-details">
          <div class="col-md-6">
            Deadline
          </div>
          <div class="col-md-6">
            28.08.2016
          </div>
          <p>Szczegóły</p>
          <div class="content">
            Wybór sukni ślubnej jest jedną z najtrudniejszych decyzji przy organizacji wesela. Każda przyszła panna młoda chce w tym dniu wyglądać pięknie i podkreślić swoje walory. Warto więc, zamiast kierować się przemijającymi trendami, zastanowić się, jaki krój
            będzie najlepiej pasował do naszej figury i pięknie podkreśli to, co najlepsze w naszej sylwetce.
          </div>
          <div class="btn btn-warning">update</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/checklist/new.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div class='container'>
  <div class="header">
    <div class="logo">
      <img src="http://blog.weddly.co/wp-content/uploads/2016/08/logo-3-1.png" class="logo">
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="menu col-md-3">
        <div class="leftMenu">
          <h3>Łukasz and Renata</h3>
          <div class="row">
            <div class="col-md-6">
              Do zrobienia
            </div>
            <div class="col-md-6">
              6
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              Zrobione
            </div>
            <div class="col-md-6">
              3
            </div>
          </div>
        </div>
      </div>
      <div class="checklist col-md-5">
        <div class="month">
          <h3>August</h3>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
      </div>
      <div class="menu3 col-md-4">
        <div class="item">
          New item
        </div>
        <div class="item-details">
          <div class="col-md-6">
            Deadline
          </div>
          <div class="col-md-6">
            28.08.2016
          </div>
          <p>Szczegóły</p>
          <div class="content">
            Wybór sukni ślubnej jest jedną z najtrudniejszych decyzji przy organizacji wesela. Każda przyszła panna młoda chce w tym dniu wyglądać pięknie i podkreślić swoje walory. Warto więc, zamiast kierować się przemijającymi trendami, zastanowić się, jaki krój
            będzie najlepiej pasował do naszej figury i pięknie podkreśli to, co najlepsze w naszej sylwetce.
          </div>
          <div class="btn btn-warning">update</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weddly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/help.html.erb
<div class="container" id="registration">
  <div class="logo" id="logo">
    <img src="http://blog.weddly.co/wp-content/uploads/2016/08/logo-3-1.png">
  </div>
  <p> Za chwilię zaczniesz planować wesele </p>
  <form>
    <div class="form-group">
        <input type="text" class="form-control" id="your-name" placeholder="Twoje imię">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="partners-name" placeholder="Imię partnera">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="date" placeholder="Data wesela">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-warning">Zacznij planować wesele</button>
    </div>
  </form>
</div>

app/views/static_pages/home.html.erb
<div class='container'>
  <div class="header">
    <div class="logo">
      <img src="http://blog.weddly.co/wp-content/uploads/2016/08/logo-3-1.png" class="logo">
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="menu col-md-3">
        <div class="leftMenu">
          <h3>Łukasz and Renata</h3>
          <div class="row">
            <div class="col-md-6">
              Do zrobienia
            </div>
            <div class="col-md-6">
              6
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              Zrobione
            </div>
            <div class="col-md-6">
              3
            </div>
          </div>
        </div>
      </div>
      <div class="checklist col-md-5">
        <div class="month">
          <h3>August</h3>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
      </div>
      <div class="menu3 col-md-4">
        <div class="item">
          New item
        </div>
        <div class="item-details">
          <div class="col-md-6">
            Deadline
          </div>
          <div class="col-md-6">
            28.08.2016
          </div>
          <p>Szczegóły</p>
          <div class="content">
            Wybór sukni ślubnej jest jedną z najtrudniejszych decyzji przy organizacji wesela. Każda przyszła panna młoda chce w tym dniu wyglądać pięknie i podkreślić swoje walory. Warto więc, zamiast kierować się przemijającymi trendami, zastanowić się, jaki krój
            będzie najlepiej pasował do naszej figury i pięknie podkreśli to, co najlepsze w naszej sylwetce.
          </div>
          <div class="btn btn-warning">update</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
	<%= f.text_field :content, placeholder: "New Todo" %>
	<%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
	<% if todo_item.completed? %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% else %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p><%= todo_item.content %></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag params[:controller] %>

<body class="home">

<div class="container registration">

  <div class="logo" id="logo">
    <img src="http://blog.weddly.co/wp-content/uploads/2016/08/logo-3-1.png">
  </div>
  <p> Za chwilię zaczniesz planować wesele </p>
  <form>
    <div class="form-group">
        <input type="text" class="form-control" id="your-name" placeholder="E-mail">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="partners-name" placeholder="Hasło">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-warning">Sign Up</button>
    </div>
  </form>
  <div class="row">
    <div class=" signup">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
      <%= f.text_field :name, placeholder: "name", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.email_field :email, placeholder: "email", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.password_field :password, placeholder: "Hasło", class: "form-control" %>
    </div>
      <div class="form-group">
      <%= f.password_field :password_confirmation,
            placeholder: "Potwierdzenie hasła",
            class: "form-control" %>
          </div>
          <div class="form-group">
      <%= f.submit "Create my account", class: "btn btn-warning" %>
    </div>
    <% end %>
  </div>
  </div>
</div>
<%= debug(params) if Rails.env.development? %>
</body>

app/views/users/show.html.erb
<%= stylesheet_link_tag params[:controller] %>

<div class="col-md-8">
    <% if @user.checklist_items.any? %>
      <h3>Microposts (<%= @user.checklist_items.count %>)</h3>
      <ol class="microposts">
        <%= render @checklist_items %>
      </ol>
      <%= will_paginate @checklist_items %>
    <% end %>
  </div>

<div class='container'>
  <div class="header2">
    <div class="logo2">
      <img src="http://blog.weddly.co/wp-content/uploads/2016/08/logo-3-1.png" class="logo">
    </div>
  </div>
  <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
  <div class="container">
    <div class="row">
      <div class="menu col-md-3">
        <div class="leftMenu">
          <h3><%= gravatar_for @user %>
          <%= @user.name %></h3>
          <%= @user.name %>, <%= @user.email %>
          <div class="row">
            <div class="col-md-6">
              Do zrobienia
            </div>
            <div class="col-md-6">
              6
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              Zrobione
            </div>
            <div class="col-md-6">
              3
            </div>
          </div>
        </div>
      </div>
      <div class="checklist col-md-5">
        <div class="month">
          <h3>August</h3>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="date col-md-1">
          <h4>1<br>PN</h4>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
        <div class="col-md-11">
          <div class="col-md-2">
            <img src="http://blog.weddly.co/wp-content/uploads/2016/08/Ring-1.png" class="ring">
          </div>
          <div class="item col-md-10">
            Budżet
          </div>
        </div>
      </div>
      <div class="menu3 col-md-4">
        <div class="item">
          New item
        </div>
        <div class="item-details">
          <div class="col-md-6">
            Deadline
          </div>
          <div class="col-md-6">
            28.08.2016
          </div>
          <p>Szczegóły</p>
          <div class="content">
            Wybór sukni ślubnej jest jedną z najtrudniejszych decyzji przy organizacji wesela. Każda przyszła panna młoda chce w tym dniu wyglądać pięknie i podkreślić swoje walory. Warto więc, zamiast kierować się przemijającymi trendami, zastanowić się, jaki krój
            będzie najlepiej pasował do naszej figury i pięknie podkreśli to, co najlepsze w naszej sylwetce.
          </div>
          <div class="btn btn-warning">update</div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= debug(params) if Rails.env.development? %>